"""Idempotent seed data for inventory tables (Nexova material catalog)."""

from __future__ import annotations

SYSTEM_SEED_USER_UUID = "00000000-0000-4000-8000-000000000001"

INVENTORY_SEED: dict = {
    "assets": [
        {
            "name": "B2B sales certification kit",
            "sku": "NXV-KIT-B2B-VLC",
            "category": "training_kit",
            "office": "Valencia",
            "programme_id": "b2b-sales",
            "reorder_threshold": 5,
        },
        {
            "name": "B2B sales certification kit",
            "sku": "NXV-KIT-B2B-MIA",
            "category": "training_kit",
            "office": "Miami",
            "programme_id": "b2b-sales",
            "reorder_threshold": 5,
        },
        {
            "name": "Basic leadership certificate pack",
            "sku": "NXV-CERT-LEAD-VLC",
            "category": "certification",
            "office": "Valencia",
            "programme_id": "basic-leadership",
            "reorder_threshold": 3,
        },
        {
            "name": "Support onboarding manual",
            "sku": "NXV-ONB-SUP-MIA",
            "category": "onboarding_equipment",
            "office": "Miami",
            "programme_id": "support-onboarding",
            "reorder_threshold": 4,
        },
        {
            "name": "Access credential set",
            "sku": "NXV-ONB-CRED-VLC",
            "category": "onboarding_equipment",
            "office": "Valencia",
            "programme_id": "support-onboarding",
            "reorder_threshold": 2,
        },
        {
            "name": "Leadership facilitation kit",
            "sku": "NXV-KIT-LEAD-MIA",
            "category": "training_kit",
            "office": "Miami",
            "programme_id": "basic-leadership",
            "reorder_threshold": 5,
        },
        # Keep prior SKU used by stock tests with remapped material category
        {
            "name": 'Laptop 14" Business (onboarding)',
            "sku": "NXV-IT-001",
            "category": "onboarding_equipment",
            "office": "Valencia",
            "programme_id": "support-onboarding",
            "reorder_threshold": 5,
        },
        {
            "name": "Leadership training workbook",
            "sku": "NXV-TRN-001",
            "category": "training_kit",
            "office": "Valencia",
            "programme_id": "basic-leadership",
            "reorder_threshold": 4,
        },
    ],
    "entries": [
        {
            "sku": "NXV-IT-001",
            "quantity": 10,
            "supplier": "TechDistrib Valencia S.L.",
            "office": "Valencia",
            "currency": "EUR",
            "unit_cost": 820.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-IT-001",
            "quantity": 5,
            "supplier": "TechDistrib Valencia S.L.",
            "office": "Valencia",
            "currency": "EUR",
            "unit_cost": 820.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-KIT-B2B-VLC",
            "quantity": 20,
            "supplier": "PrintWorks Valencia",
            "office": "Valencia",
            "currency": "EUR",
            "unit_cost": 45.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-KIT-B2B-MIA",
            "quantity": 15,
            "supplier": "PrintWorks Miami",
            "office": "Miami",
            "currency": "USD",
            "unit_cost": 52.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-CERT-LEAD-VLC",
            "quantity": 12,
            "supplier": "PrintWorks Valencia",
            "office": "Valencia",
            "currency": "EUR",
            "unit_cost": 18.5,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-ONB-SUP-MIA",
            "quantity": 25,
            "supplier": "Office Depot Miami",
            "office": "Miami",
            "currency": "USD",
            "unit_cost": 12.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-ONB-CRED-VLC",
            "quantity": 40,
            "supplier": "SecureID EU",
            "office": "Valencia",
            "currency": "EUR",
            "unit_cost": 6.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-KIT-LEAD-MIA",
            "quantity": 10,
            "supplier": "PrintWorks Miami",
            "office": "Miami",
            "currency": "USD",
            "unit_cost": 38.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-TRN-001",
            "quantity": 30,
            "supplier": "PrintWorks Valencia",
            "office": "Valencia",
            "currency": "EUR",
            "unit_cost": 22.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        # Price spike seed for variance narrative (>10% vs 52)
        {
            "sku": "NXV-KIT-B2B-MIA",
            "quantity": 5,
            "supplier": "PrintWorks Miami",
            "office": "Miami",
            "currency": "USD",
            "unit_cost": 60.0,
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
    ],
    "exits": [
        {
            "sku": "NXV-IT-001",
            "quantity": 3,
            "exit_type": "allocation",
            "assigned_to": "agent-uuid-001",
            "office": "Valencia",
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-KIT-B2B-VLC",
            "quantity": 4,
            "exit_type": "allocation",
            "assigned_to": "consultant-uuid-002",
            "office": "Valencia",
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-ONB-CRED-VLC",
            "quantity": 35,
            "exit_type": "consumption",
            "assigned_to": None,
            "office": "Valencia",
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
        {
            "sku": "NXV-ONB-SUP-MIA",
            "quantity": 22,
            "exit_type": "allocation",
            "assigned_to": "agent-uuid-003",
            "office": "Miami",
            "user_uuid": SYSTEM_SEED_USER_UUID,
        },
    ],
}
